# Generated by Django 3.2.8 on 2021-10-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_relationships', '0002_frameeorks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frameeorks',
            new_name='Frameworks',
        ),
    ]
